require("ryanzola.plugins-setup")
require("ryanzola.core.options")
require("ryanzola.core.keymaps")
require("ryanzola.core.colorscheme")
require("ryanzola.plugins.comment")
require("ryanzola.plugins.nvim-tree")
require("ryanzola.plugins.lualine")
require("ryanzola.plugins.telescope")
require("ryanzola.plugins.nvim-cmp")
require("ryanzola.plugins.lsp.mason")
require("ryanzola.plugins.lsp.lspsaga")
require("ryanzola.plugins.lsp.lspconfig")
require("ryanzola.plugins.lsp.null-ls")
require("ryanzola.plugins.autopairs")
require("ryanzola.plugins.treesitter")
require("ryanzola.plugins.gitsigns")

